
version: '3.8'
services:
  mongo-bagel:
    image: mongo:noble
    container_name: mongo-bagel
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bagel-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bagel-backend:
    image: thebagelproject/bagel-backend
    container_name: bagel-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
#      - NODE_ENV=production
#      - PORT=5000
#      - MONGO_URI=mongodb://mongo-bagel:27017/BagelDB
#      - SESSION_COOKIE_SECRET= 
#      - JWT_SECRET=  
#      - PAT_ENCRYPTION_KEY= 
    depends_on:
      mongo-bagel:
        condition: service_healthy
    networks:
      - bagel-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  bagel-ui:
    image: thebagelproject/bagel-ui
    container_name: bagel-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=http://bagel-backend:5000
    depends_on:
      - bagel-backend
    networks:
      - bagel-network

  bagel-server:
    image: thebagelproject/bagel-server
    container_name: bagel-server
    restart: unless-stopped
    depends_on:
      - mongo-bagel
    networks:
      - bagel-network
    # Add environment variables and ports as needed

volumes:
  mongo_data:
    driver: local

networks:
  bagel-network:
    driver: bridge
